# Generated by Django 2.2.3 on 2019-09-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AddField(
            model_name='tasklist',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
